sudo: required

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -a allow-uri-read  **/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html-archive asciidoctor/docker-asciidoctor asciidoctor -a allow-uri-read archive/**/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html-root asciidoctor/docker-asciidoctor asciidoctor -a allow-uri-read *.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf **/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf-archive asciidoctor/docker-asciidoctor asciidoctor-pdf archive/**/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf-root asciidoctor/docker-asciidoctor asciidoctor-pdf *.adoc

after_error:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  - docker logs asciidoc-to-html-archive
  - docker logs asciidoc-to-pdf-archive
  - docker logs asciidoc-to-html-root
  - docker logs asciidoc-to-pdf-root

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  - docker logs asciidoc-to-html-archive
  - docker logs asciidoc-to-pdf-archive
  - docker logs asciidoc-to-html-root
  - docker logs asciidoc-to-pdf-root

after_success:
  - find . -name '*html' | cpio -pdm output ;
  - find . -name '*pdf' | cpio -pdm output ;
  - find . -name '*png' | cpio -pdm output ;
  - find . -name '*jpg' | cpio -pdm output ;
  - find . -name '*jpeg' | cpio -pdm output ;
  - cd output ;
  - find -name "*.html" -exec sed -i 's/class="article"/class="article toc2 toc-left"/g' {} +
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
